// <auto-generated />
using System;
using DateSeed;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;

namespace DateSeed.Migrations
{
    [DbContext(typeof(Exemplo))]
    partial class ExemploModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28124")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DateSeed.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.SeedData(new[]
                    {
                        new { Id = new Guid("87ab8b47-e8fc-4fd4-8a13-3f03c61886dc"), Descricao = "Ativo" },
                        new { Id = new Guid("3e0f3725-3a7b-4687-a164-58439b9f386a"), Descricao = "Desativado" },
                        new { Id = new Guid("b6ee8a4b-164c-4294-9e46-6368d8c31070"), Descricao = "SPC" },
                        new { Id = new Guid("8972714b-04d9-46e6-b006-40487a6252ed"), Descricao = "Outros" }
                    });
                });
#pragma warning restore 612, 618
        }
    }
}
